### ISSUE TITLE
Howto use with flatpaked Steam?

### ISSUE THREAD

**Issue by Pshemas** [Matoking/protontricks#11]
I wonder - does anyone know howto use Protontricks when you use flatpaked Steam? Would be awesome if it could be done -I've switched to Flatpak Steam as it gave the least amount of issues (to be precise - no issues at all :D ), but there are still games that require tweaks when using Proton and I'd love to have an easy way to apply those.

**Comment by Pshemas** [comment]
update: it seems to work on my end without any extra hassle. Mostly because I created symlinks to flatpaked steam folders so I could get Flatpak Steam under Lutris. It seems to do the trick ;) for Protontricks as well.

**Comment by Matoking** [comment]
I tested the Flatpak version of Steam for a bit, and the following seems to work. **There are limitations since the environment inside the Steam sandbox is missing a lot of packages.** Some winetricks commands complain about the missing `cabextract` package, but you can use `winecfg`, for example.

The following instructions are based on the comment by @BoltsJ [here](https://github.com/Sirmentio/protontricks/issues/44#issuecomment-457990974).

---

First, launch a new shell inside the Steam sandbox by running the following command.

`flatpak run --command=bash com.valvesoftware.Steam`

Install protontricks inside this shell using pipx:

```
python3 -m pip install --user pipx
.local/bin/pipx install protontricks
```

Then install winetricks:

```
curl https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks -o winetricks
chmod +x winetricks
```

Now, exit the sandboxed shell and create an alias called `protontricks-flat` that can be used to call protontricks for the Flatpak version of Steam. You can change the name of the alias if you want to.

```
exit
echo "alias protontricks-flat='flatpak run --env=WINETRICKS=$HOME/winetricks --command=.local/bin/protontricks com.valvesoftware.Steam'" >> ~/.bashrc
```

Finally, close the terminal and reopen it. **You should now be able to use protontricks using the alias you chose (`protontricks-flat` is the default).** For example:

```
protontricks-flat -s deus ex
```

**Comment by Matoking** [comment]
I've added the Flatpak installation instructions [to the wiki](https://github.com/Matoking/protontricks/wiki/Usage-with-Flatpak-Steam).
