### ISSUE TITLE
How do I use STEAM_DIR command

### ISSUE THREAD

**Issue by VexedDiagram22** [Matoking/protontricks#114]
I cant figure out how to use the command my steam path is /home/vexeddiagarm22/.var/app/com.valvesoftware.Steam
and where my games are here /home/vexeddiagarm22/.var/app/com.valvesoftware.Steam/SteamLibrary
thank you in advance.

**Comment by Matoking** [comment]
Are you using the Flatpak version of Steam? In that case, you will need to install the Flatpak specific version of Protontricks. You can find the instructions [here](https://github.com/flathub/com.valvesoftware.Steam.Utility.protontricks#readme).

---

The `STEAM_DIR` environment variable is intended for more unusual use cases, and they can be set globally in different places, or only for the current command like this:

```
$ STEAM_DIR=/different/path/to/steam protontricks --gui
```

You can read more about setting environment variables [here](https://wiki.archlinux.org/title/Environment_variables#Defining_variables). However, I think the problem here is probably due to Steam being installed using Flatpak.

**Comment by VexedDiagram22** [comment]
Thank you that worked!
