### ISSUE TITLE
Protontricks is extremely slow

### ISSUE THREAD

**Issue by Meister1593** [Matoking/protontricks#120]
**Describe the bug**
When running protontricks, it's expected to work pretty much exactly how winetricks would (in terms of performance), even under bwrap it shouldn't produce too bad results. But in reality everything that i do with protontricks runs like 5 times slower. Even if i do `--no-bwrap` - it's still extremely slow.

**To Reproduce**
1. Try installing anything on any game using protontricks (in my case it's dotnet 4.8, or faudio, doesnt matter much)
2. Protontricks installs at least 5 times slower than it should

**Expected behavior**
Protontricks shouldn't run **that** slow

**System:**
 - Distro: Void Linux
 - Protontricks version: protontricks (1.6.0)
 - Steam version: Both beta and stable are affected, checked this case on laptop too

**Additional context**
I use fish under bash, and thought it might be related, but - winetricks anyway runs under sh and winetricks works fine
In logs i noticed that wine-gecko couldn't be found, but i do have it installed system-wide (though it's only 1 file (`/usr/share/wine/gecko/wine-gecko-2.47.2-x86.msi`) and i probably need to install it manually?
At the same time this wine-gecko line appears every time it *stops* or *hangs* which introduces a lot of delays
Protontricks is also slow even on another pc with the same distro (Void)

**If the error happens when trying to run a Protontricks command, run the command again using the `-v` flag and copy the output!**
It's not a full log because it takes at least 20 mins to go only halfway through and painfully slow
[protontricks_log](https://gist.github.com/Meister1593/2fea91f079bcb49818da4b7beb5af3d4)

**Comment by jarrard** [comment]
Yeah it has run slower for me also with all proton versions inc GE. Still eventually gets the job done...

**Comment by Matoking** [comment]
I've looked into this issue again and have been working on a feature to improve startup time. The WIP version of the fix can be found in [keep_wineserver_alive](https://github.com/Matoking/protontricks/tree/keep_wineserver_alive) branch.

The short version is that the change decreases startup time for a single Wine command from ~6 seconds to around 1.7 seconds:

```
# Before
$ protontricks -c "perf stat -r 5 wine cmd.exe /c echo %AppData%" 740130
5,9531 +- 0,0205 seconds time elapsed  ( +-  0,34% )

# After
$ protontricks -c "perf stat -r 5 wine cmd.exe /c echo %AppData%" 740130
1,725 +- 0,317 seconds time elapsed  ( +- 18,40% )
```

If you're using pipx, you can install the WIP fix like so:

```
$ pipx install --force git+https://github.com/Matoking/protontricks.git@keep_wineserver_alive
```

I'll look into pushing a new version with the improvement after some more work, since slow performance with Winetricks has been a sticking point for a long time.

---

The longer version is that a large part of why bwrap has been so slow is that every individual Wine command also causes a wineserver (roughly analogous to Linux's init process) to be started up and shut down during each command. This isn't a problem when bwrap is not used, since the wineserver is not bound to a single Wine process and can continue execution in the background. With bwrap, however, each container is cleaned up after running the command, taking the Wine process and the wineserver inside it with it as well.

The solution is to instead launch the wineserver in a separate container and keep it alive for the entire duration of the Protontricks command, after which it is terminated. Since each container shares the same process namespace, other Wine processes are able to use the wineserver even if it's launched inside a different container, greatly decreasing startup time.

**Comment by Matoking** [comment]
I've pushed the aforementioned change and another performance fix into the development branch. The second fix reuses an existing container instead of launching one for each Wine command (which feels somewhat obvious in hindsight). With both of these changes in place, the startup time has been reduced drastically for the default configuration with bwrap enabled:

```
# Before (consistently ~6 seconds)
$ protontricks -c "perf stat -r 5 wine cmd.exe /c echo %AppData%" 740130
5,9531 +- 0,0205 seconds time elapsed  ( +-  0,34% )

# After (settles around 0.4 seconds after a short warmup) 
$ protontricks -c "perf stat -r 5 wine cmd.exe /c echo %AppData%" 740130
0.929 +- 0.671 seconds time elapsed  ( +- 72.19% )
```

The "background wineserver" is only enabled for bwrap by default, but you can force it manually using the `--background-wineserver` command-line flag (eg. `protontricks --background-wineserver <appid> <command>`). I didn't notice a great difference in startup time without bwrap, but your mileage may vary.

I'll look into releasing a new version shortly with the performance improvements, but you can install the development version using the instructions in the README to use them immediately.
