### ISSUE TITLE
Failed to create direct3d device error message after enabling galliumnine

### ISSUE THREAD

**Issue by tatsujb** [Matoking/protontricks#15]
I ran the following :

```
wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
chmod +x winetricks
wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks.bash-completion
sudo mv winetricks /usr/bin
sudo mv winetricks.bash-completion /usr/share/bash-completion/completions/winetricks
python3 -m pip install --user pipx
~/.local/bin/pipx ensurepath
eval "$(cat .bashrc | tail -n +10)"
pipx install protontricks
pipx upgrade protontricks
protontricks 9420 galliumnine
```

before this the game ran fine. 

after it though, I get the "Failed to create direct3d device" error box.

What am I doing wrong?

the game is using the default wineprefix (64bit) perhaps that's wrong?

my launch arguments in steam for this game (which worked before said commands) are the following : 

`PROTON_NO_ESYNC=1, PROTON_DUMP_DEBUG_COMMANDS=1, PROTON_USE_GALLIUM_NINE=1, PROTON_GALLIUM_NINE_MODULEPATH="/usr/lib/i386-linux-gnu/d3d/d3dadapter9.so.1:/usr/lib/x86_64-linux-gnu/d3d/d3dadapter9.so.1" %command%`

**Comment by Matoking** [comment]
The "64-bit wineprefix" message can be ignored, as that happens with all Proton games.

You can try running `protontricks -c 'wine ninewinecfg' <appid>` to check if Gallium Nine is installed correctly.

Since this is a Gallium Nine related issue, I'm closing this issue for now. You can check the [wine-nine-standalone](https://github.com/iXit/wine-nine-standalone) repo for further help.
