### ISSUE TITLE
Protontricks won't launch on Steam Deck

### ISSUE THREAD

**Issue by The-Hoff** [Matoking/protontricks#171]
As the title says. There is no response when clicking 'launch'. Other Deck users are experiencing the same. 
Any help would be most appreciated; thanks.

**Comment by Matoking** [comment]
This seems to be a duplicate of #169.

I'm guessing you're clicking the "Launch" button in the Discover software manager? That's a known bug with Discover, which will be fixed in Plasma 5.26. It's scheduled to be released to the general public on 6th of October, though I have no idea when it will make its way to SteamOS 3, unfortunately; that's up to Valve.
