### ISSUE TITLE
Docs on preferred install method for steam deck?

### ISSUE THREAD

**Issue by jgarvin** [Matoking/protontricks#175]
The README covers many installation methods, but it's not clear which is the default/preferred way for a Steam Deck user. For example it says if you're running the flat version of Steam do X,Y,Z but I have no idea if that's true for the factory install of the deck. protontricks appears in the Discover app, but I assume that installs a flatpak, and I found an old reddit thread saying that doesn't put it in PATH, so I'm left unsure what the most official/supported way of doing things is. Any clarity would be appreciated.

**Comment by Matoking** [comment]
I've updated the README to clarify this.

In short, **Flatpak is the recommended option for Steam Deck**. While you should be able to unlock the filesystem and then install Protontricks using either a community AUR package or pipx, those installations would be wiped by an OS update due to how SteamOS 3's A/B partitioning works, on top of requiring more manual effort.

---

You may not need to add Protontricks to `PATH`. Adding an application to `PATH` is usually done to make it easier to run it on the command-line.

Instead, you can use the instructions under [the Flatpak section](https://github.com/Matoking/protontricks#flatpak-recommended) to make it possible to use the `protontricks` alias. This is often useful if you want to run a command listed on ProtonDB, for example. Without the alias, you'd have to run

```
flatpak run com.github.Matoking.protontricks 1234 foo bar
```

instead of

```
protontricks 1234 foo bar
```

which is a bit more cumbersome and harder to remember. With the alias, you can just copy a command and run it directly as-is.

**Comment by jgarvin** [comment]
Thanks,🙏
