### ISSUE TITLE
Can't change prefix

### ISSUE THREAD

**Issue by Chicorice** [Matoking/protontricks#184]
**Describe the bug**
The application always reverts back to the default prefix, no matter what I do.

**To Reproduce**
1. Opening Protontricks from the application launcher.
2. It tells you to select a Steam app.
3. Pick one that requires a 32bit prefix.
4. Fail to open and be told you're using a 64-bit WINEPREFIX. Hit Okay.
5. Be taken to the "Winetricks - Choose a wineprefix" page. The default prefix is selected.
6. Select either "Create new wineprefix", make a 32bit one, and close the app. Or pick the 32bit one you've already made.
7. Either way, next I automatically end up on the page "Winetricks - current prefix is "/home/blah blah blah prefix I selected"". 
8. Do nothing, just hit OK.
9. Be taken back to "Winetricks - choose a wineprefix". The default prefix is still selected.
10. Process repeats, and the 32bit prefix never seems to remain selected when I restart the app to open the game I want to play.

**Expected behavior**
Upon selecting my own custom prefix, and hitting OK right away after being asked if i would like to change anything and being given the options, I expect to be able to choose a game with the prefix I selected.

**System (please complete the following information):**
 - Distro: [SteamOS 3.3.2]
 - Protontricks installation method: The Discover store.
 - Protontricks version: 1.9.2
 - Steam version: Current update (16 Nov 2022)

**Comment by Matoking** [comment]
Proton only supports 64-bit prefixes and there is no official way to create a 32-bit prefix as far as I know. Is there a reason you're trying to create a 32-bit prefix?

The warning about "64-bit prefix" is caused by Winetricks and can be ignored. I'll probably look into patching it out in the Flatpak version of Protontricks, given that it's a common source of confusion.

**Comment by Chicorice** [comment]
I want to play some rpgmaker games, specifically Yume 2kki and .flow, and when I try to run them with the default prefix I'm told to switch to a 32-bit prefix.

**Comment by Matoking** [comment]
I don't know exactly what application suggests switching to a 32-bit prefix, but there's a chance it assumes you're running the normal Wine instead of Proton. In that case, using Wine instead of Proton might be a better option. One solution _might_ be installing Bottles and running the game through that instead; it allows you to select Wine with a 32-bit prefix:

https://flathub.org/apps/details/com.usebottles.bottles
