### ISSUE TITLE
SteamOS protontricks prefixes previously ran, but now won't.

### ISSUE THREAD

**Issue by witherpiggy** [Matoking/protontricks#185]
Steam OS on Steam Deck 512GB:

I have been using protontricks to try to run the program Reloaded-II. However, on first attempt, when trying to run any .exe through a game's prefix, nothing happened, and neither protontricks nor the protontricks-launch command worked. I factory reset my desk, tried again, and it worked. However, now the same issue has reäppeared, and whenever I attempt to launch any application, nothing happens without so much as an error message, and as I said, the console will not work at all. I have attempted to reïnstall protontricks to no avail. I know that the .exe still works as when I run the game through Games Mode the process starts. Could any help be gleaned for this infuriating issue?

**Comment by Matoking** [comment]
What do you mean exactly by the console not working (eg. the Konsole application in desktop mode won't launch at all)? From your comment, I take it you've run the `protontricks` and `protontricks-launch` commands manually in desktop mode? If you do so, but also add the `-v` flag, like in the following example, what is printed?
I'm assuming you've installed the Flatpak version of Protontricks through Discover.

```
flatpak run --command=protontricks-launch com.github.Matoking.protontricks -v <exe file>
```

For example, open the directory with the EXE file in Dolphin, click F4 to open the console tab and enter the command there. Assuming Protontricks is installed, it should print _something_ at the very least with the `-v` flag.

**Comment by erxkum** [comment]
I'm having a similar if not the same problem:

`Operating System: SteamOS 3.3.2
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-valve21.3-1-neptune (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Custom APU 0405
Memory: 14.5 GiB of RAM
Graphics Processor: AMD Custom GPU 0405`

When I run protontricks it opens the gui to select an app, but when I choose an app, nothing happens and after a 10 or so seconds the process terminates, It worked a few months ago, so I don't really know what happened in the meantime.

I tried to tinker around to try to fix the issue, after awhile I figured it was something I did on the OS that screwed the configuration or something along those lines and that I couldn't figure out what and reset the Steam Deck fo factory settings, deleting all my data, only to find out the issue remained.

I tried to search on google for similar issues and fixes, I admit I'm not knowledgeable with linux but I'm learning I tried:
using --no-brwap and I tried using another app called Flatseal to give it more permissions(I literally ticked everything on) but no good.

I tried installing using discover and then deleted the app and tried `flatpak install flathub com.github.Matoking.protontricks`

Using -v gives me the following results:
`**(deck@steamdeck ~)$ protontricks -v --gui**
protontricks (INFO): Running inside Flatpak sandbox, version 1.12.4.
protontricks (INFO): Found Steam directory at /home/deck/.local/share/Steam
protontricks (INFO): Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 1 Steam library folders
protontricks (INFO): Currently logged-in Steam user: irxson
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
protontricks (INFO): Using 'yad' as GUI provider`

*GUI opens and I choose Cyberpunk*

`protontricks (INFO): The current device is a Steam Deck
protontricks (INFO): We're on a Steam Deck, checking if compatibility profile is available for the app
protontricks (INFO): App has Steam Deck compatibility profile with Proton version: proton-stable
protontricks (INFO): Found active compatibility tool: Proton 7.0
protontricks (INFO): Active compatibility tool is a Proton installation
protontricks (INFO): Using 'bwrap = True' as default value
protontricks (INFO): Using 'background-wineserver = True' as default value
protontricks (INFO): Using separately installed Steam Runtime: Steam Linux Runtime - Soldier
protontricks (INFO): Running Steam Runtime using bwrap containerization.
If any problems arise, please try running the command again using the `--no-bwrap` flag and make an issue report if the problem only occurs when bwrap is in use.
protontricks (INFO): Created Steam Runtime Wine binary directory at /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 7.0/bin
protontricks (INFO): WINE environment variable is not available. Setting WINE environment variable to Proton bundled version.
protontricks (INFO): WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
protontricks (INFO): Starting bwrap launcher process: /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 7.0/bin/bwrap-launcher
protontricks (INFO): Starting wineserver keepalive process: /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 7.0/bin/wineserver-keepalive
protontricks (INFO): Attempting to run command ['/app/bin/winetricks', '--gui']
protontricks - bwrap-launcher 19: Following directories will be mounted inside container: /app /etc /home /sbin /tmp
protontricks - bwrap-launcher 19: Using temporary directory: /tmp/protontricks-0iloj4zp
protontricks - wineserver-keepalive 20: Starting wineserver-keepalive process...

(process:55): Gtk-WARNING **: 09:38:32.879: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 09:38:32.880: Failed to load module "canberra-gtk-module"
winetricks GUI enabled, using zenity 3.43.0
steam-runtime-launcher-service[201]: W: The --socket option is deprecated. Prefer to use --session or --bus-name.
Executing mkdir -p /home/deck/.local/share/Steam/steamapps/compatdata/1091500
                                                                             ------------------------------------------------------
                                                                                                                                   warning: Você está usando um WINEPREFIX de 64-bit. Observe que muitos casos instalam apenas versões de pacotes de 32-bit. Se você encontrar problemas, teste novamente em um WINEPREFIX limpo de 32-bit antes de relatar um bug.
                                                                                                                                        ------------------------------------------------------
                                                                                                                                                                                              Using winetricks 20220411 (protontricks-flatpak) - sha256sum: 7742386ba997512fc50088dc66dc6119946de735a62b0a7f0763cd3b1924abbd with wine-7.0 and WINEARCH=win64

                                                                                                                                  (process:2622): Gtk-WARNING **: 09:40:28.780: Locale not supported by C library.
                                                                                                                                                                                                                        Using the fallback 'C' locale.
                           Gtk-Message: 09:40:28.780: Failed to load module "canberra-gtk-module"
                                                                                                 This option is not available. Please see --help for all possible usages.
                                                                                                                                                                         protontricks (INFO): Terminating wineserver keepalive process 20
              protontricks (INFO): Terminating launcher process 19
                                                                  protontricks - wineserver-keepalive 20: Cleanup finished, goodbye!
                                                                                                                                    protontricks (INFO): Launcher process terminated
                                                                                                                                                                                    (deck@steamdeck ~)$`

After this the konsole acts weird, because I can type commands, but they don't show up while writing them, only after I press enter.

**Comment by witherpiggy** [comment]
turns out all i needed to do was launch desktop mode through settings instead of by holding the power button, and, what ho, it works as intended.

**Comment by SCKitkat** [comment]
I've also used reloaded II, but I did the desktop setting thing, but non of the exes I've run will still get proton tricks to work
