### ISSUE TITLE
Warn users if ( or danger of )  using older winetricks

### ISSUE THREAD

**Issue by JJones780** [Matoking/protontricks#197]
Older versions of winetricks will install older versions of DLLs !
  
A warning that an older version of winetricks will result in older DLLs  would be welcome!

See https://github.com/ValveSoftware/Proton/issues/3106 as an example of where this warning might've helped.

**Comment by Matoking** [comment]
I looked into implementing this, but turns out Winetricks already has an automatic check for version updates. However, it's disabled under Debian and likely other derivatives:

```
    # In Debian we don't connect automatically to a remote site for privacy reasons.
    #winetricks_latest_version_check
```
The page for Winetricks also specifically points out Debian / Ubuntu as distros that usually ship outdated Winetricks versions and where manual install is preferred instead. As such, I don't think implementing a version check that mostly caters for one family of distros -- and is redundant on others -- would be worth the maintenance effort.

The easy option would be to recommend manual install or Flatpak instead for Debian / Ubuntu, but I fear the README is already getting a bit convoluted.

**Comment by JJones780** [comment]
I can relate to your concern about maintainability and the information might be lost in the readme.  Hopefully places like protondb can make people aware of the issue well enough. 

OTOH, a simple check for winetricks version > x might avoid some protontricks bug reports as well as alleviating dll issues.
