### ISSUE TITLE
Faudio installer 404 

### ISSUE THREAD

**Issue by dusanyu** [Matoking/protontricks#21]
faudi installer fails with 
Executing cd /home/cmg/.cache/winetricks/faudio
Downloading https://web.archive.org/web/2000/https://github.com/Kron4ek/FAudio-Builds/releases/download/git-a756af4/faudio-git-a756af4.tar.xz to /home/cmg/.cache/winetricks/faudio
--2019-06-15 19:13:10--  https://web.archive.org/web/2000/https://github.com/Kron4ek/FAudio-Builds/releases/download/git-a756af4/faudio-git-a756af4.tar.xz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving web.archive.org (web.archive.org)... 207.241.233.214
Connecting to web.archive.org (web.archive.org)|207.241.233.214|:443... connected.
HTTP request sent, awaiting response... 404 NOT FOUND
2019-06-15 19:13:11 ERROR 404: NOT FOUND.

------------------------------------------------------
Downloading https://web.archive.org/web/2000/https://github.com/Kron4ek/FAudio-Builds/releases/download/git-a756af4/faudio-git-a756af4.tar.xz failed
------------------------------------------------------

**Comment by Matoking** [comment]
It seems you've already reported [the issue at the Winetricks repo](https://github.com/Winetricks/winetricks/issues/1258) and received a response that should solve the issue.  You may need to install [the latest version of Winetricks](https://github.com/Winetricks/winetricks#installing) from GitHub in order to install FAudio.
