### ISSUE TITLE
Not launching on Steam Deck

### ISSUE THREAD

**Issue by KochevnikRUS** [Matoking/protontricks#249]
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 639, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'P'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/app/lib/python3.10/site-packages/protontricks/cli/main.py", line 264, in main
    steam_app = select_steam_app_with_gui(
  File "/app/lib/python3.10/site-packages/protontricks/gui.py", line 318, in select_steam_app_with_gui
    appid2icon = _get_appid2icon(steam_apps, steam_path=steam_path)
  File "/app/lib/python3.10/site-packages/protontricks/gui.py", line 104, in _get_appid2icon
    resized_img.save(icon_cache_path)
  File "/app/lib/python3.10/site-packages/PIL/Image.py", line 2413, in save
    save_handler(self, fp, filename)
  File "/app/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 642, in _save
    raise OSError(msg) from e
OSError: cannot write mode P as JPEG

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.12.4.
Found Steam directory at /home/deck/.local/share/Steam
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Currently logged-in Steam user: serkanvolad
Shortcut Spotify (3696751144) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Found 7 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider
App icon /home/deck/.local/share/Steam/appcache/librarycache/238010_icon.jpg has unusual size, resizing

**Comment by Slvrtnge** [comment]
Hi similar issue I think! Seems like it's mostly affecting non steam games? Like my emulated ones and other shortcuts. This is my error message:

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 639, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/app/lib/python3.10/site-packages/protontricks/cli/main.py", line 264, in main
    steam_app = select_steam_app_with_gui(
  File "/app/lib/python3.10/site-packages/protontricks/gui.py", line 318, in select_steam_app_with_gui
    appid2icon = _get_appid2icon(steam_apps, steam_path=steam_path)
  File "/app/lib/python3.10/site-packages/protontricks/gui.py", line 104, in _get_appid2icon
    resized_img.save(icon_cache_path)
  File "/app/lib/python3.10/site-packages/PIL/Image.py", line 2413, in save
    save_handler(self, fp, filename)
  File "/app/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 642, in _save
    raise OSError(msg) from e
OSError: cannot write mode RGBA as JPEG


=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.12.4.
Found Steam directory at /home/deck/.local/share/Steam
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Multiple compatdata directories found for app 1205520
Multiple compatdata directories found for app 2349870
Multiple compatdata directories found for app 1202900
Multiple compatdata directories found for app 701160
Multiple compatdata directories found for app 1629520
Multiple compatdata directories found for app 2212330
Multiple compatdata directories found for app 17390
Multiple compatdata directories found for app 1369340
Multiple compatdata directories found for app 1493710
Multiple compatdata directories found for app 1282730
Currently logged-in Steam user: rainbowroro
Shortcut Discord (2758416756) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Citra (2174991349) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Dolphin (emulator) (2169977985) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut RPCS3 (3038681132) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut yuzu (Emulator) (2666692479) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Kirby 64: The Crystal Shards (4260552023) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pokémon Snap (3271873221) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut 007: Nightfire (4153671896) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Billy Hatcher and the Giant Egg (2429890626) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Custom Robo (2420536194) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Digimon World 4 (3321952619) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Kirby Air Ride (2439130805) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Star Fox Assault (2635585137) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Metroid Prime: Hunters (2957652106) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Files (3198203107) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut ProtonUp-Qt (2949253153) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Remote Play Whatever (3778033522) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Mario Party Superstars (2306004405) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Mario Kart 8 Deluxe (2205964658) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Metroid Prime 2: Echoes (2903270647) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut EmuDeck (2663973902) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Super Smash Bros. Ultimate (3995942175) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Found 0 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider
App icon /home/deck/.local/share/Steam/appcache/librarycache/473690_icon.jpg has unusual size, resizing

**Comment by Matoking** [comment]
Try updating to 1.10.5 if you haven't already; it should fix this issue.

**Comment by KochevnikRUS** [comment]
> 

Yaaay, it works!

Thanks for the update on this situation
