### ISSUE TITLE
validity check fails

### ISSUE THREAD

**Issue by wingfielda** [Matoking/protontricks#34]
Making package: protontricks 1.3-1 (Sat 09 Nov 2019 06:17:57 PM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found 1.3.tar.gz
==> Validating source files with sha512sums...
    1.3.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!

**Comment by Matoking** [comment]
This is an issue with the community maintained AUR package that has a wrong SHA512 checksum for some reason. This can only be fixed by the package maintainer.

As a workaround you can replace the sha512sum in the PKGBUILD with `eb99ca9548cde2fa73705b838b7cb93c7b76460a9d96bb69aeaad772f304f37c9e0eb2481e9123145825a7379bd9d998a0fbeb52f77adf663d5c49bcff61be20`.
