### ISSUE TITLE
Protontricks unable to see winetricks (manually installed)

### ISSUE THREAD

**Issue by jatin-cbs** [Matoking/protontricks#42]
I have protontricks installed using pipx and winetricks manually installed in Downloads. protontricks is unable to see it it just says winetricks not found when I run protontricks..

**Comment by Matoking** [comment]
Please check the [installation instructions for Winetricks](https://github.com/Winetricks/winetricks#installing). If you're using Ubuntu or Debian (those tend to ship outdated versions of Winetricks), you can download the latest version of winetricks, mark it as executable and then move it to `/usr/bin` like this:

```
# Create and switch to a temporary directory writeable by current user. See:
#   https://www.tldp.org/LDP/abs/html/subshells.html
cd "$(mktemp -d)"

# Download the latest winetricks script (master="latest version") from Github.
wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks

# Mark the winetricks script (we've just downloaded) as executable. See:
#   https://www.tldp.org/LDP/GNU-Linux-Tools-Summary/html/x9543.htm
chmod +x winetricks

# Move the winetricks script to a location which will be in the standard user PATH. See:
#   https://www.tldp.org/LDP/abs/html/internalvariables.html
sudo mv winetricks /usr/bin
```

The reason you need to install winetricks into a path such as `/usr/bin/winetricks` is so that other programs can find it without having to provide the full path. You can run `echo $PATH` to see what directories are searched.
