### ISSUE TITLE
python-versioneer creates nondeterministic tarballs

### ISSUE THREAD

**Issue by winny-** [Matoking/protontricks#44]
See also #34.

I downloaded https://github.com/Matoking/protontricks/archive/1.3.1.tar.gz on December 29th and again today (January 11th) and the files differ.

| url | date | size | sha512sum | 
| --- | --- | --- | --- |
| https://github.com/Matoking/protontricks/archive/1.3.1.tar.gz | 2019-12-29 | 57793 | `1c00668c4132b5a1caef088dfd282ddfa59b6ec5485a273e83d513d93258964894e05b0cdefdbad5ffde9e78498f0f24236382772695f6b9d9caf0f243889bf4` |
| https://github.com/Matoking/protontricks/archive/1.3.1.tar.gz | 2020-01-11 | 57784 | `4e33334e219db2e6679b430ee42408529478834c80c7da3b9bece4756eb27b9331d49a6a884de8a7ced5ec29d78ce831fee4cfbf6d5adcd750666b7e7a1e5607` |

### Diff between the two tarballs

```diff
diff -ruN protontricks-1.3.1-2019-12-29/src/protontricks/_version.py protontricks-1.3.1-2020-01-11/src/protontricks/_version.py
--- protontricks-1.3.1-2019-12-29/src/protontricks/_version.py  2019-11-21 10:14:11.000000000 -0600
+++ protontricks-1.3.1-2020-01-11/src/protontricks/_version.py  2019-11-21 10:14:11.000000000 -0600
@@ -23,7 +23,7 @@
     # setup.py/versioneer.py will grep for the variable names, so they must
     # each be defined on a line of their own. _version.py will just call
     # get_keywords().
-    git_refnames = " (HEAD -> master, tag: 1.3.1)"
+    git_refnames = " (tag: 1.3.1)"
     git_full = "db7f1abf7bcd8786836d8c03e25d539ccc8686ff"
     git_date = "2019-11-21 18:14:11 +0200"
     keywords = {"refnames": git_refnames, "full": git_full, "date": git_date}
```

The impact is this breaks most package managers.

**Comment by Matoking** [comment]
Interesting; it seems that GitHub uses git-archive to create zip/tar.gz files on demand, which means the identical source code files can cause a different archive to be created depending on if the tagged commit is the head of the repo (it was on December 29th) or not (it wasn't anymore on January 11th) when the tar.gz file is downloaded. This is because Protontricks uses [python-versioneer](https://github.com/warner/python-versioneer) to derive the version number from the git tag, and that in turn relies on the string `$Format:%d$` which is replaced with either of the two strings by git-archive depending on the situation.

This (hopefully) means that the string won't change again for past releases, but I'll have to look into using another library to handle the "git tag -> package version" problem to prevent the issue from happening again. python-versioneer seems to have been unmaintained for a long time, so it's probably a good idea to replace it anyway.

**Comment by Matoking** [comment]
I migrated to setuptools-scm which is used by many Python projects. It fixes the non-deterministic tarball problem, but comes with two changes that affect packaging:

* setuptools-scm is required to build the package. All distros that have unofficial Protontricks packages also ship Python packages that use setuptools-scm, so this shouldn't be a problem.
* **GitHub tarballs/git-archive no longer provide the version number and don't support packaging.** You will have to use PyPI tarballs (see [this section](https://wiki.archlinux.org/index.php/Python_package_guidelines#Source) on Arch Linux wiki for details) or clone the git repository with the version tags intact.
