### ISSUE TITLE
Confusing 'usage' message.

### ISSUE THREAD

**Issue by thaewrapt** [Matoking/protontricks#56]
Usage message (shown when something is wrong with command-line parameters), suggests a wrong order of parameters:

`usage: protontricks [-h] [--verbose] [-s SEARCH [SEARCH ...]] [-c COMMAND] [--gui] [--no-runtime] [-V] [appid] ...`

AFAIK, _appid_ should always be a first parameter.

**Comment by Matoking** [comment]
The order of parameters is correct: you have to put Protontricks related parameters first. The dots at the end (`...`) denote where you should put the Winetricks parameters, but the auto-generated message does not make this clear.

---

The parameters in the usage message (`--verbose`, `-s SEARCH`, etc.) are parameters that Protontricks itself supports, and must be added _before_ the app ID. This is because the parameters _after_ the app ID are given to Winetricks as-is without any validation. Protontricks doesn't know what parameters your Winetricks installation supports, and trying to detect which parameters are Protontricks related and which are Winetricks related would be extremely difficult.

For example, this is a valid command:
```
$ protontricks --no-runtime 377160 --gui
# GUI is shown as expected
```

but this isn't
```
$ protontricks 377160 --no-runtime --gui
# Winetricks doesn't know what to do with `--no-runtime`
------------------------------------------------------
unknown option --no-runtime
-----------------------------------------------------
```

Flags like `-v` are also accepted by both applications, so you can do this:
```
$ protontricks -v 377160 -v --gui
# Verbose flag is enabled for both Protontricks and Winetricks
```

**Comment by thaewrapt** [comment]
Thanks for the clarification, I'm aware of this as I use protontricks on a regular basis, but there is nothing about this (I mean, winetricks parameters) in the message I quoted. Maybe, it needs a special mention there?

Also, looking at `protontricks -h` output I actually see a mention of 'winetricks_command' once — in 'positional arguments' section, maybe it's possible to substitute '...' with it? I guess it should make more sense for people not so familiar with a tool.

**Comment by thaewrapt** [comment]
Btw, returning to my first post, I still see some confusion for '--gui' parameter. Do both protontricks and winetricks support it?

**Comment by Matoking** [comment]
I'll look into clarifying the message when using incorrect parameters. The usage message alone is really terse, so it's probably better to show the full help message instead if the command is incorrect. This is already done in some cases.

---

Winetricks has a `--gui` flag that forces GUI even if the environment seems to be non-interactive. `--gui` in Protontricks means that the user will be prompted to choose the game from a dropdown list, which will then open the Winetricks GUI for that game.

**Comment by thaewrapt** [comment]
> 

> I'll look into clarifying the message when using incorrect parameters. The usage message alone is really terse, so it's probably better to show the full help message instead if the command is incorrect. This is already done in some cases.

Agreed, that should give an end-user much more insight (and above all things, unify things some).
 
> Winetricks has a `--gui` flag that forces GUI even if the environment seems to be non-interactive. `--gui` in Protontricks means that the user will be prompted to choose the game from a dropdown list, which will then open the Winetricks GUI for that game.

Thanks, now it's clear.

**Comment by thaewrapt** [comment]
Thanks for fixing!
