### ISSUE TITLE
[Feature Request] A Application menu shortcut of the protontricks gui

### ISSUE THREAD

**Issue by Toadfield** [Matoking/protontricks#77]
I hate it to open a terminal everytime I want to use that program.

**Comment by Matoking** [comment]
You can make a shortcut yourself by creating the following file at `~/.local/share/applications/Protontricks.desktop`:

```
[Desktop Entry]
Exec=protontricks --gui
Name=Protontricks
Type=Application
Terminal=false
Categories=Utility;
Icon=system-software-install
```

---

Protontricks itself doesn't install a shortcut since it's published as a Python package. Python packages are commonly installed in a virtualenv (an isolated environment), and installing desktop shortcuts even when inside this environment would violate that guideline. Unofficial packages listed in the README don't have this restriction, however.

**Comment by Matoking** [comment]
I've added two desktop files in the development version: one that adds an app shortcut as described in this issue, and another that allows EXE files to be launched using Protontricks (useful for 3rd party mods and patches).

The limitation with Python packages still exists, so if you're installing using pip/pipx, you'll have to install them manually using `protontricks-desktop-install` command that comes with the package. Ideally, other package platforms such as distro package maintainers will take care of this by installing the desktop files correctly and removing the `protontricks-desktop-install` executable, meaning the user doesn't have to do anything for it to work.
