### ISSUE TITLE
Cannot Install WMP11 with Protontricks (Permission Denied)

### ISSUE THREAD

**Issue by ThisNekoGuy** [Matoking/protontricks#97]
**Describe the bug**
I'm trying to install WMP11 for the Resident Evil 1 Remaster (304240) and I can't due to "Permission denied" errors during the installation

**To Reproduce**
1. Run command `protontricks 304240 -q -f wmp11`
2. Command fails and "Permission denied" error is displayed

**Expected behavior**
WMP11 should install without issue.

**System (please complete the following information):**
 - Distro: Arch Linux
 - Protontricks version: 1.5.0
 - Steam version: Non-beta

**Additional context**

**If the error happens when trying to run a Protontricks command, run the command again using the `-v` flag and copy the output!**

https://gist.github.com/ThisNekoGuy/1a1f4513ae1bc495753c29b03f4fdf18

The `--no-bwrap` flag also doesn't work (it claims it's an unknown command).

The installation works if I use winetricks instead though, but the game still doesn't load to the main menu.
` WINEPREFIX="/mnt/bigStorage/Gaming/SteamLibrary/steamapps/compatdata/304240/" winetricks -q -f wmp11`

**Comment by Matoking** [comment]
You have to provide `--no-bwrap` as one of the first parameters (ie. before `30420`) so that Protontricks picks it up instead of Winetricks. Any parameters *after* `30420` are passed to Winetricks. In your case, please try running the following command instead:

```
$ protontricks -v --no-bwrap 304240 -q -f -v wmp11
```

I'll look into improving documentation so that this behavior is better explained.

It's possible the "Permnission denied" issue is related to winetricks/winetricks#1648. If the problem still occurs after using the aforementioned command with the `--no-bwrap` flag, then it's most likely out of scope for Protontricks and needs to be fixed in the Winetricks or Proton side of things.

**Comment by ThisNekoGuy** [comment]
[Log](https://gist.github.com/ThisNekoGuy/8eabab027e10d83f7a665db301ee0357)

It still fails with the same error(s) but I found that installing it with Proton 5.0-10 then upgrading the Proton version afterwards works.

**Comment by Matoking** [comment]
OK, seems like it's the upstream bug. Closing this issue.

**Comment by mfizia** [comment]
Just in case someone one wants to workaround this issue. It's strongly not recommend to set the permissions to 777 for your proton installation, cause protontricks / winetricks will override the original dll from your proton installation. 

**With a little bit of work you can still just change the dlls in your prefix and not in your proton installation!**

As we learned in the upstream issue for [`winetricks`](https://github.com/Winetricks/winetricks/issues/1648) the problem are the symlinks to the dlls. 

So everytime you see an error message like:
`/home/<user>/.steam/debian-installation/steamapps/compatdata/<gameid>/pfx/dosdevices/c:/windows/syswow64/dswave.dll: Permission denied` - you got a dll symlink to your proton installation.

Remove the symlink with `rm`.
e.g.: `rm /home/<user>/.steam/debian-installation/steamapps/compatdata/<gameid>/pfx/dosdevices/c\:/windows/syswow64/dswave.dll`

After you removed the symlink, you will get a step further. Restart the installation. If there is another dll symlink, who is blocking the installation, just repeat the procedure.

In my case `directmusic` should be installed. Ended up with this:
```
rm /home/<user>/.steam/debian-installation/steamapps/compatdata/<gameid>/pfx/dosdevices/c\:/windows/syswow64/dmband.dll 
rm /home/<user>/.steam/debian-installation/steamapps/compatdata/<gameid>/pfx/dosdevices/c\:/windows/syswow64/dmcompos.dll 
rm /home/<user>/.steam/debian-installation/steamapps/compatdata/<gameid>/pfx/dosdevices/c\:/windows/syswow64/dmime.dll 
rm /home/<user>/.steam/debian-installation/steamapps/compatdata/<gameid>/pfx/dosdevices/c\:/windows/syswow64/dmloader.dll 
rm /home/<user>/.steam/debian-installation/steamapps/compatdata/<gameid>/pfx/dosdevices/c\:/windows/syswow64/dmscript.dll 
rm /home/<user>/.steam/debian-installation/steamapps/compatdata/<gameid>/pfx/dosdevices/c\:/windows/syswow64/dmstyle.dll 
rm /home/<user>/.steam/debian-installation/steamapps/compatdata/<gameid>/pfx/dosdevices/c\:/windows/syswow64/dmsynth.dll 
rm /home/<user>/.steam/debian-installation/steamapps/compatdata/<gameid>/pfx/dosdevices/c\:/windows/syswow64/dmusic.dll 
rm /home/<user>/.steam/debian-installation/steamapps/compatdata/<gameid>/pfx/dosdevices/c\:/windows/syswow64/dmusic32.dll 
rm /home/<user>/.steam/debian-installation/steamapps/compatdata/<gameid>/pfx/dosdevices/c\:/windows/syswow64/dsound.dll 
rm /home/<user>/.steam/debian-installation/steamapps/compatdata/<gameid>/pfx/dosdevices/c\:/windows/syswow64/dswave.dll 
WINEPREFIX="/home/<user>/.steam/debian-installation/steamapps/compatdata/<gameid>/pfx" winetricks directmusic
```

**Comment by TheSmallBlue** [comment]
For those that are watching this issue, here's an update since I've been keeping up with this since I personally had it.

This issue originates from kyz/libmspack, which is the library from which cabextract comes from. Cabextract is what winetricks uses to install programs such as WMP11, but it did not support the symlinks that proton creates (as far as i understand, versions of proton from 5.0 upwards stopped pasting the same files over and over when making app's wineprefixes and started making symlinks instead).

You can see the issue in question at kyz/libmspack/issues/42
Recently, a PR that fixes this issue has finally been finished, this being kyz/libmspack/pull/43
And our upstream, Winetricks, has recently made a PR that should bring those changes over Winetricks/winetricks/pull/2025

So, what's next now is to wait for winetricks's PR to be merged, for ProtonTricks to pull that PR, and finally, this issue will be fixed.
